name: CI

on:
  push:
    branches: [canary]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Install depedencies
        run: yarn --frozen-lockfile --check-files
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            */*/lib
            !node_modules

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Install depedencies
        run: yarn --frozen-lockfile --check-files
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Install depedencies
        run: yarn --frozen-lockfile --check-files
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - run: yarn lint

  pass:
    runs-on: ubuntu-latest
    needs: [build, lint, test]
    steps:
      - run: exit 0

  publish:
    runs-on: ubuntu-latest
    needs: [pass]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Install depedencies
        run: yarn --frozen-lockfile --check-files
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Fetch all git tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Configure git user
        run: |
          git config --local user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_USER_NAME }}"
      - run: ./scripts/publish.sh
